name: Create release on tag push

on:
  push:
    tags:
      - 'release/*'

jobs:
  build:
    name: Build the_vault-tweaks
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle Wrapper
        run: chmod +x ./gradlew && ./gradlew build

      - name: Draft release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/libs/the_vault-tweaks-1.18.2-*.jar"
          bodyFile: "CHANGELOG.md"
          draft: true
